id = "marksman"
name = "Marksman"
description = "Marksman support for Markdown files."
version = "0.0.2"
schema_version = 1
authors = ["Vitaly Slobodin <vitaliy.slobodin@gmail.com>"]
repository = "https://github.com/vitallium/zed-marksman"

[language_servers.marksman]
name = "Marksman"
language = "Markdown"
